;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=None
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Survivor",DevComment="")
+GameplayTagList=(Tag="Survivor.Motivation.Attack",DevComment="")
+GameplayTagList=(Tag="Survivor.Motivation.Search",DevComment="")
+GameplayTagList=(Tag="Survivor.Motivation.Wander",DevComment="")

